#!/bin/bash

cname=g.e213.T62_g17.0024
st_arc_dir=/lustre/wrk/misumi/cesm2/archive
n=5  # 除外する年数

target_dir=$st_arc_dir"/"$cname"/ocn/hist"
echo $target_dir

# ファイルリストを取得し、ソートする
h_list=$(find "$target_dir" -name "$cname.*.h.????-??.nc" | sort -n -t. -k4,4 -k5,5)

# 最後のn年分の年を特定する
last_n_years=$(echo "$h_list" | grep -o '\.h\.[0-9]\{4\}' | sort -u | tail -n $n | cut -d'.' -f3)

echo $last_n_years

# 最後のn年分のファイルを除外する
h_list_filtered=$(echo "$h_list" | grep -v "\.h\.$(echo "$last_n_years" | paste -sd'|' -)")

echo "$h_list_filtered"