#!/bin/bash

cname=g.e213.T62_g17.0024
st_arc_dir=/lustre/wrk/misumi/cesm2/archive

target_dir=$st_arc_dir'/'$cname'/ocn/hist'
echo $target_dir

file_list=$(find "$target_dir" -name "$cname.*.h.????-??.nc")

echo "File list:"
echo "$file_list"