#!/bin/bash

st_arc_dir=/lustre/wrk/misumi/cesm2/archive
n=5  # Number of years to exclude

# Define case names, directories, and file types
case_names=("g.e213.T62_g17.0024" "g.e213.T62_g17.0025")
directories=("ocn/hist" "ice/hist")
ocn_file_types=("h" "dd" "do" "dt" "dv" "h.ecosys.nday1" "h.nday1")
ice_file_types=("h")

for cname in "${case_names[@]}"
do
    for dir in "${directories[@]}"
    do
        target_dir=$st_arc_dir"/"$cname"/"$dir

        if [ "$dir" == "ocn/hist" ]; then
            file_types=("${ocn_file_types[@]}")
            file_pattern="$cname.pop.%s.????-??*"
        elif [ "$dir" == "ice/hist" ]; then
            file_types=("${ice_file_types[@]}")
            file_pattern="$cname.cice.%s.????-??.nc"
        fi

        for ft in "${file_types[@]}"
        do
            # Get the file list and sort it
            file_list=$(find "$target_dir" -name "$(printf "$file_pattern" "$ft")" | sort -n -t. -k5,5 -k6,6)

            # Identify the last n years
            last_n_years=$(echo "$file_list" | sed -E 's/.*\.(pop|cice)\.'$ft'\.([0-9]{4})-[0-9]{2}.*/\2/' | sort -u | tail -n $n)

            # Exclude files from the last n years
            file_list_filtered=$(echo "$file_list" | grep -vE "\.(pop|cice)\.$ft\.($(echo "$last_n_years" | paste -sd'|' -))-[0-9]{2}")

            # Print the filtered file list only if it's not empty
            if [ -n "$file_list_filtered" ]; then
                echo "$file_list_filtered"
            fi
        done
    done
done